import type { LucideIcon } from "lucide-react";
import {
  AudioLines,
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  ChartLine,
  Code2,
  Coins,
  FolderOpen,
  Gamepad2,
  Globe,
  GraduationCap,
  Heart,
  Image,
  Layers,
  LayoutGrid,
  Megaphone,
  Newspaper,
  PenLine,
  Search,
  Shield,
  ShoppingBag,
  Sparkles,
  Trophy,
  Users,
  UserRound,
  Plane,
  Home,
  Link2,
} from "lucide-react";

const BY_SLUG: Record<string, LucideIcon> = {
  all: LayoutGrid,
  leaderboards: Trophy,
  seo: Search,
  marketing: Megaphone,
  productivity: Layers,
  agents: Bot,
  crypto: Coins,
  other: Sparkles,
  developer: Code2,
  health: Heart,
  business: Briefcase,
  games: Gamepad2,
  ecommerce: ShoppingBag,
  travel: Plane,
  directories: FolderOpen,
  agencies: Building2,
  "ai-media": Image,
  education: GraduationCap,
  social: Users,
  people: UserRound,
  design: PenLine,
  hiring: Users,
  domains: Link2,
  security: Shield,
  sales: ChartLine,
  news: Newspaper,
  "real-estate": Home,
  writing: BookOpen,
  audio: AudioLines,
  analytics: ChartLine,
};

export function categoryIcon(slug: string): LucideIcon {
  return BY_SLUG[slug] ?? Globe;
}
