/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as HowRankingWorksRouteImport } from './routes/how-ranking-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DailyIndexRouteImport } from './routes/daily.index'
import { Route as DailyDateRouteImport } from './routes/daily.$date'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as AuthenticatedCreditsBuyRouteImport } from './routes/_authenticated/credits.buy'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiPublicOgLSlugRouteImport } from './routes/api/public/og/l.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRankingWorksRoute = HowRankingWorksRouteImport.update({
  id: '/how-ranking-works',
  path: '/how-ranking-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DailyIndexRoute = DailyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DailyRoute,
} as any)
const DailyDateRoute = DailyDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => DailyRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreditsBuyRoute = AuthenticatedCreditsBuyRouteImport.update({
  id: '/credits/buy',
  path: '/credits/buy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgLSlugRoute = ApiPublicOgLSlugRouteImport.update({
  id: '/api/public/og/l/$slug',
  path: '/api/public/og/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/daily': typeof DailyRouteWithChildren
  '/how-ranking-works': typeof HowRankingWorksRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/l/$slug': typeof LSlugRoute
  '/daily/': typeof DailyIndexRoute
  '/daily/$date': typeof DailyDateRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/credits/buy': typeof AuthenticatedCreditsBuyRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/public/og/l/$slug': typeof ApiPublicOgLSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/daily': typeof DailyIndexRoute
  '/how-ranking-works': typeof HowRankingWorksRoute
  '/checkout': typeof CheckoutIndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/l/$slug': typeof LSlugRoute
  '/daily/$date': typeof DailyDateRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/credits/buy': typeof AuthenticatedCreditsBuyRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/public/og/l/$slug': typeof ApiPublicOgLSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/daily': typeof DailyRouteWithChildren
  '/how-ranking-works': typeof HowRankingWorksRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/l/$slug': typeof LSlugRoute
  '/daily/': typeof DailyIndexRoute
  '/daily/$date': typeof DailyDateRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/_authenticated/credits/buy': typeof AuthenticatedCreditsBuyRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/public/og/l/$slug': typeof ApiPublicOgLSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/daily'
    | '/how-ranking-works'
    | '/checkout'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/submit'
    | '/l/$slug'
    | '/daily/'
    | '/daily/$date'
    | '/checkout/'
    | '/checkout/success'
    | '/credits/buy'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/public/og/l/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/daily'
    | '/how-ranking-works'
    | '/checkout'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/submit'
    | '/l/$slug'
    | '/daily/$date'
    | '/checkout/success'
    | '/credits/buy'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/public/og/l/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/categories'
    | '/daily'
    | '/how-ranking-works'
    | '/checkout'
    | '/privacy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/submit'
    | '/l/$slug'
    | '/daily/'
    | '/daily/$date'
    | '/checkout/'
    | '/checkout/success'
    | '/_authenticated/credits/buy'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/public/og/l/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  DailyRoute: typeof DailyRouteWithChildren
  HowRankingWorksRoute: typeof HowRankingWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  LSlugRoute: typeof LSlugRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiPublicOgLSlugRoute: typeof ApiPublicOgLSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-ranking-works': {
      id: '/how-ranking-works'
      path: '/how-ranking-works'
      fullPath: '/how-ranking-works'
      preLoaderRoute: typeof HowRankingWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/': {
      id: '/daily/'
      path: '/'
      fullPath: '/daily/'
      preLoaderRoute: typeof DailyIndexRouteImport
      parentRoute: typeof DailyRoute
    }
    '/daily/$date': {
      id: '/daily/$date'
      path: '/$date'
      fullPath: '/daily/$date'
      preLoaderRoute: typeof DailyDateRouteImport
      parentRoute: typeof DailyRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/credits/buy': {
      id: '/_authenticated/credits/buy'
      path: '/credits/buy'
      fullPath: '/credits/buy'
      preLoaderRoute: typeof AuthenticatedCreditsBuyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/l/$slug': {
      id: '/api/public/og/l/$slug'
      path: '/api/public/og/l/$slug'
      fullPath: '/api/public/og/l/$slug'
      preLoaderRoute: typeof ApiPublicOgLSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DailyRouteChildren {
  DailyIndexRoute: typeof DailyIndexRoute
  DailyDateRoute: typeof DailyDateRoute
}

const DailyRouteChildren: DailyRouteChildren = {
  DailyIndexRoute: DailyIndexRoute,
  DailyDateRoute: DailyDateRoute,
}

const DailyRouteWithChildren = DailyRoute._addFileChildren(DailyRouteChildren)

interface CheckoutRouteChildren {
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(CheckoutRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedCreditsBuyRoute: typeof AuthenticatedCreditsBuyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedCreditsBuyRoute: AuthenticatedCreditsBuyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  DailyRoute: DailyRouteWithChildren,
  HowRankingWorksRoute: HowRankingWorksRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  LSlugRoute: LSlugRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiPublicOgLSlugRoute: ApiPublicOgLSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
